### ISSUE TITLE
xvfb-run dependency

### ISSUE THREAD

**Issue by eddelbuettel** [eddelbuettel/prrd#3]
When accepting it on CRAN (with some hesitation), Uwe wrote back

```
2. xvfb-run may not available on all platforms (Mac? commercial unixes?)
Hence I'd put that in SystemRequeirements.

3. There are almost no examples nor tests, and I understadn that these are 
difficult to achive given what the package does. 
```

We can test for 2. but not sure about 3.

**Comment by dpastoor** [comment]
Hi Dirk,

I was digging into this package last night, so this issue is aligned with one I was about to create. I'm trying to understand what the purpose of xvfb-run is? At first I thought it was for security from the comment about symlink attacks. Though looking into it (briefly) it seems to be more about being able to spin up a headless server.

Looking at https://github.com/eddelbuettel/prrd/blob/master/R/dequeue.R#L68 is this because certain packages will generate plots based on the "interactive" session's screen size or is it some other reason for using it?

Perhaps I can help dig around and see if there is a suitable (windows) alternative, since xvfb does not seem to be (easily) available on windows, if at all.

**Comment by eddelbuettel** [comment]
I was just working on that on the train in.  I will generalize `dequeue` shortly.  For now (as on CRAN) consider `prrd` to be Linux only.

`xvfb-run` provides a virtual X11 environment via the framebuffer.  Ie you can run X11 apps headless.  Somethinge we have used many years.  Not sure if macOS has it though.  It may, but it may be more marginal.

**Comment by eddelbuettel** [comment]
This was taken care of in fe5796af7b2164da1f35ce2d28f9e54935ac8590 and 5304a5b4cdbf46c9e340798743146a8faf7d5d40.
